# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV.fetch("EMAIL_PROVIDER_USERNAME") %>
  email_provider_password: <%= ENV.fetch("EMAIL_PROVIDER_API_KEY") %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  domain_name: andreebrazeau.com
  owner_email: <%= ENV["OWNER_EMAIL"] %>

  secret_key_base: 9e1d7a0918b2a2f1f0ba9209d21a226a34f41620dda3a6c6411381e7267630b7b8ff6eebcd0774f0468a8fc8c04a493cfb4e94d903b5011431ce926041fd4ec9

test:
  email_provider_username: <%= ENV["EMAIL_PROVIDER_USERNAME"] %>
  email_provider_password: <%= ENV["EMAIL_PROVIDER_API_KEY"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  domain_name: andreebrazeau.com
  owner_email: <%= ENV["OWNER_EMAIL"] %>

  secret_key_base: ae899393a93347a74fb118c90ec788fc1274afcdaab7514e27caedbf7b36a23b88b1a3aea5724928fdbc629aee9b834d9f759f371cd200c6d7f0301f08b6ef93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["EMAIL_PROVIDER_USERNAME"] %>
  email_provider_password: <%= ENV["EMAIL_PROVIDER_USERNAME"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  domain_name: andreebrazeau.com
  owner_email: <%= ENV["OWNER_EMAIL"] %>

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  domain_name: <%= ENV["DOMAIN_NAME"] %>
